name: Deploy static site with secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Replace secrets in script.js
        run: |
          sed -i "s|API_KEY__|${{ secrets.API_KEY }}|g" script.js
          sed -i "s|VUE_APP_FIREBASE_AUTHDOMAIN|${{ secrets.VUE_APP_FIREBASE_AUTHDOMAIN }}|g" script.js   
          sed -i "s|VUE_APP_FIREBASE_PROJECTID|${{ secrets.VUE_APP_FIREBASE_PROJECTID }}|g" script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .